# Generated by Django 4.2.16 on 2024-12-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_slider_image_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='message2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='slider',
            name='message',
            field=models.CharField(max_length=15),
        ),
    ]
