# Generated by Django 4.2.16 on 2024-12-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_slider_message2_alter_slider_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='message',
            field=models.CharField(max_length=50),
        ),
    ]
