# Generated by Django 4.2.16 on 2024-12-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_slider_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='message2',
        ),
    ]
