# Generated by Django 4.2.16 on 2024-12-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_slider_message2_alter_slider_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='message',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='slider',
            name='message2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
